apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: "true"
  labels:
{{ include "am_combiner_integration_tests.labels" $ | indent 4 }}

  name: {{ include "am_combiner_integration_tests.fullname" $ }}
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.server.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "am_combiner_integration_tests.fullname" $ }}
          servicePort: {{ .Values.server.port }}
        path: /
