# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_config": "00_mongo_config.ipynb",
         "recursive_get": "00_mongo_config.ipynb",
         "mongo_connect": "00_mongo_config.ipynb",
         "read_mongo": "00_mongo_config.ipynb",
         "send_df_to_mongo": "00_mongo_config.ipynb",
         "get_entity_info": "01_articles_data.ipynb",
         "save_article_info": "01_articles_data.ipynb",
         "save_entity_data_from_es": "01_articles_data.ipynb",
         "save_entity_data_from_ae": "01_articles_data.ipynb",
         "from_local_to_mongo": "01_articles_data.ipynb",
         "from_mongo_to_article_df": "01_articles_data.ipynb",
         "save_mongo_entity_to_csv": "02_name_commonness.ipynb",
         "save_entity_tokens_to_csv": "02_name_commonness.ipynb",
         "get_commonness_score": "02_name_commonness.ipynb",
         "clean_spacy_date": "03-date-features.ipynb",
         "DateStandardisationVisitor": "03-date-features.ipynb",
         "nlp": "06_Coreference_Resolution.ipynb",
         "check_words": "03_Feature_Profession.ipynb",
         "ProfessionFeatureExtractor": "03_Feature_Profession.ipynb",
         "ProfessionVisitor": "03_Feature_Profession.ipynb",
         "dbpedia_response": "05_Feature_DBPedia_EntityResolution.ipynb",
         "EnitityLinkVisitor": "05_Feature_DBPedia_EntityResolution.ipynb",
         "CoreferenceResolutionVisitor": "06_Coreference_Resolution.ipynb"}

modules = ["config.py",
           "articles.py",
           "name_commonness.py",
           "features/date.py",
           "features/profession.py",
           "features/entity_linking.py",
           "features/corefresolution.py"]

doc_url = "//am_combiner"

git_url = "https://git/machine-learning/data-science-and-statistical-learning/am_combiner/tree/master/"

def custom_doc_links(name): return None
