# Source: am-combiner/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: er-feature-cache-rebuilding
  labels:
    app.kubernetes.io/name: am-combiner
    helm.sh/chart: am-combiner-0.1.0
    app.kubernetes.io/instance: er-cache-rebuilding
    app.kubernetes.io/version: "master-87cefd1d"
spec:
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: am-combiner
        app.kubernetes.io/instance: er-cache-rebuilding
      annotations:
        downscaler/exclude: "true"
    spec:
      serviceAccountName: entity-resolution-aws-access
      restartPolicy: OnFailure
      containers:
        - name: am-combiner
          image: "871716277715.dkr.ecr.eu-west-1.amazonaws.com/machine-learning/data-science-and-statistical-learning/am_combiner:feature-amc-584-954b679e"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 8000m
              memory: 24Gi
            requests:
              cpu: 4000m
              memory: 24Gi
          command:
            - python
            - am_combiner/utils/cleanup_experiments.py
          args:
            - --mongo-collection=tfidf-cosine-similairty--set-b-results-csv
            - --mongo-collection=tfidf-cosine-similairty--set-c-results-csv
            - --mongo-collection=tfidf-cosine-similairty-results-best-model-csv
            - --mongo-collection=tfidf-and-spectral-clustering-results-best-model-csv
            - --mongo-collection=tfidf-and-spectral-clustering-results-csv
            - --mongo-collection=tfidf-with-features-best-model-csv
            - --mongo-collection=tfidf-with-features-csv
            - --mongo-collection=gcn-combiner-results-set-c-csv
            - --mongo-collection=gcn-combiner-results-set-b-csv