resources:
  # Initial guess from the provision of TORCH and spacy in the pod.  May need to be higher
  limits:
    cpu: 4000m
    memory: 16Gi
  requests:
    cpu: 4000m
    memory: 12Gi

common:
  disableDownScaler: true
  # Never - if job cannot be restarted, OnFailure if it can
  restartPolicy: Never

combiners:
  - combiner_name: HeteroGCNCombiner
    enabled: true
    class: GCNHeteroCombiner
    attrs:
      model_uri: s3://ca-amt-mi-playground-1-entity-resolution-ml-models/am_hetero_12000_weighted_th_0.94.torch
      config_uri: s3://ca-amt-mi-playground-1-entity-resolution-ml-models/am_hetero_12000_weighted_th_0.94.json
      cache: am_combiner/data/models/
      node_features: Features.TFIDF_FULL_TEXT_12000
      use_features:
        - Features.ORG_CLEAN
        - Features.PERSON_CLEAN
        - Features.GPE_CLEAN
        - Features.LOC
        - Features.AM_CATEGORY
  - combiner_name: HeteroGCNCombinerOld
    enabled: true
    class: GCNHeteroCombiner
    attrs:
      model_uri: s3://ca-amt-mi-playground-1-entity-resolution-ml-models/hetero_12000_weighted_th_0.96.torch
      config_uri: s3://ca-amt-mi-playground-1-entity-resolution-ml-models/hetero_12000_weighted_th_0.96.json
      cache: am_combiner/data/models/
      node_features: Features.TFIDF_FULL_TEXT_12000
      use_features:
        - Features.ORG_CLEAN
        - Features.PERSON_CLEAN
        - Features.GPE_CLEAN
        - Features.LOC

experiments:
  - experimentId: setagridsearch
    numRuns: 30
    numParallel: 10
    args:
      - --mongo-collection=random_uncommon_v2_test_set
      - --input-data-source=random
      - --name-set-distribution-summarizer-class=A
      - --true-profiles-distribution-summarizer-class=A
      - --mongo-output-collection=htr-combiner-results-set-a

  - experimentId: setbgridsearch
    numRuns: 30
    numParallel: 10
    args:
      - --mongo-collection=random_uncommon_v2_test_set
      - --input-data-source=random
      - --name-set-distribution-summarizer-class=B
      - --true-profiles-distribution-summarizer-class=B
      - --mongo-output-collection=htr-combiner-results-set-b-am

  - experimentId: setcgridsearch
    numRuns: 30
    numParallel: 10
    args:
      - --mongo-collection=random_uncommon_v2_test_set
      - --input-data-source=random
      - --name-set-distribution-summarizer-class=C
      - --true-profiles-distribution-summarizer-class=C
      - --mongo-output-collection=htr-combiner-results-set-c-am
