resources:
  limits:
    cpu: 4000m
    memory: 16Gi
  requests:
    cpu: 4000m
    memory: 12Gi

common:
  disableDownScaler: true
  restartPolicy: Never

combiners:
  - combiner_name: TFIDFCosineSimilarityCombiner
    enabled: true
    class: TFIDFCosineSimilarityCombiner
    attrs:
      source_feature: Features.TFIDF_FULL_TEXT
      th:
        - 0.2

experiments:

  - experimentId: setbgridsearch
    numRuns: 30
    numParallel: 10
    args:
      - --mongo-collection=random_uncommon_v2_test_set
      - --input-data-source=random
      - --name-set-distribution-summarizer-class=A
      - --true-profiles-distribution-summarizer-class=A
      - --mongo-output-collection=tfidf-cosine-similairty-results-best-model-set-a