resources:
  limits:
    cpu: 8000m
    memory: 16Gi
  requests:
    cpu: 4000m
    memory: 12Gi

common:
  disableDownScaler: true
  restartPolicy: Never

combiners:
  - combiner_name: TFIDFAndFeaturesCosineSimilarityCombiner
    enabled: true
    class: TFIDFAndFeaturesCosineSimilarityCombiner
    attrs:
      use_features:
        - Features.PERSON_CLEAN
        - Features.ORG_CLEAN
        - Features.GPE_CLEAN
        - Features.LOC
      th:
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
      max_energy:
        - 5
        - 10
        - 15
        - 20
        - 25
        - 30
        - 35
        - 40
        - 45
        - 50
        - 55
        - 60
        - 65
        - 70
        - 75
        - 80

experiments:
  - experimentId: setagridsearch
    numRuns: 30
    numParallel: 10
    args:
      - --mongo-collection=random_uncommon_v2_set
      - --input-data-source=random
      - --name-set-distribution-summarizer-class=A
      - --true-profiles-distribution-summarizer-class=A
      - --mongo-output-collection=tfidf-with-features-set-a
  - experimentId: setbgridsearch
    numRuns: 30
    numParallel: 10
    args:
      - --mongo-collection=random_uncommon_v2_set
      - --input-data-source=random
      - --name-set-distribution-summarizer-class=B
      - --true-profiles-distribution-summarizer-class=B
      - --mongo-output-collection=tfidf-with-features-set-b
  - experimentId: setcgridsearch
    numRuns: 30
    numParallel: 10
    args:
      - --mongo-collection=random_uncommon_v2_set
      - --input-data-source=random
      - --name-set-distribution-summarizer-class=C
      - --true-profiles-distribution-summarizer-class=C
      - --mongo-output-collection=tfidf-with-features-set-c