image:
  repository: 871716277715.dkr.ecr.eu-west-1.amazonaws.com/machine-learning/entity-resolution/am_combiner
  pullPolicy: Always

serviceAccount:
  name: entity-resolution-aws-access

resources:
  limits:
    cpu: 8000m
    memory: 16Gi
  requests:
    cpu: 4000m
    memory: 12Gi

server:
  enabled: override
  portName: http
  port: 8000

  ingress:
    host: k8s.euw1.mi-playground-1.uk

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

containerProbe:
  initialDelay: 10
  period: 60
